emit:
  - "@typespec/openapi3"
options:
  "@typespec/openapi3":
    output-file: "{project-root}/appPackage/apiSpecificationFile/roadmap-openapi.json"
    omit-unreachable-types: false
    new-line: lf
